---
- hosts: master
  tasks:
    - name: Installing k3s on master
      shell:
        cmd: curl -sfL https://get.k3s.io | sh -
      become: true
    - name: Get k3s token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      become: true 
    - name: Get credentials
      command: cat /etc/rancher/k3s/k3s.yaml
      register: k3s_password
      become: true
    - debug:
        msg: "Default password is {{ k3s_password }}"
- hosts: k8s_workers
  vars:
    K3S_URL: "https://{{ hostvars['master']['ansible_eth0']['ipv4']['address'] }}:6443"
    K3S_TOKEN: "{{ hostvars['master']['k3s_token']['stdout_lines'][0]}}"
  tasks:
    - name: Installing k3s on worker nodes
      shell:
        cmd: "curl -sfL https://get.k3s.io | K3S_URL={{ K3S_URL }} K3S_TOKEN={{ K3S_TOKEN }} sh -"
      become: true

    - debug:
        msg: " {{ K3S_URL }}"
    - debug:
        msg: " {{ K3S_TOKEN }}"

