---
- hosts: master
  tasks:
    - openssh_keypair:
        path: /home/pi/.ssh/id_rsa
    - name: fetch public ssh keys
      shell:
        cmd: cat ~/.ssh/id_rsa.pub
      register: ssh_key
    - name: check key
      debug: msg="{{ ssh_key.stdout }}"
- hosts: master:k8s_workers
  tasks:
  - name: Deploying ssh key
    authorized_key: user=pi key="{{ item }}"
    with_items: "{{ hostvars['master']['ssh_key'].stdout }}"
- hosts: master
  tasks:
    - name: Installing k3sup
      shell:
        cmd: "curl -sLS https://get.k3sup.dev | sh"
      become: true
    - name: Installing k3s on master
      command: "k3sup install --ip {{  ansible_eth0.ipv4.address }} --user pi --ssh-key /home/pi/.ssh/id_rsa"
      become: true
    - name: Installing k3s on workers and joining master
      command: "k3sup join --server-ip {{  ansible_eth0.ipv4.address }} --ip {{ hostvars[item]['ansible_eth0']['ipv4']['address'] }} --user pi --ssh-key /home/pi/.ssh/id_rsa"
      become: true       
      with_items: "{{ groups['k8s_workers'] }}"
